version: '3.8'

services:
  portfolio:
    container_name: portfolio
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: docker.pkg.github.com/coryball/portfolio/portfolio
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
